# Generated by Django 2.2.5 on 2020-08-18 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
    ]
